// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaImpresion.Datos.Contexto;

#nullable disable

namespace SistemaImpresion.Datos.Migrations
{
    [DbContext(typeof(SistemaImpresionDbContext))]
    [Migration("20260105031334_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("DireccionIP")
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<bool>("Exitosa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MensajeError")
                        .HasColumnType("text");

                    b.Property<int>("TipoAccion")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("text");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Fecha", "UsuarioId", "TipoAccion");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Puesto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NumeroEmpleado")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AltoMM")
                        .HasColumnType("integer");

                    b.Property<int>("AnchoMM")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContenidoZPL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Etiquetas");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Impresion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("AutorizadoPorId")
                        .HasColumnType("integer");

                    b.Property<int?>("AutorizadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("DireccionIPOrigen")
                        .HasColumnType("text");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashZPL")
                        .HasColumnType("text");

                    b.Property<int>("ImpresoraId")
                        .HasColumnType("integer");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("MensajeError")
                        .HasColumnType("text");

                    b.Property<string>("MotivoDenegacion")
                        .HasColumnType("text");

                    b.Property<string>("Resultado")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AutorizadoPorId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EtiquetaId");

                    b.HasIndex("ImpresoraId");

                    b.HasIndex("LoteId");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("FechaSolicitud", "MaquinaId", "Estado");

                    b.ToTable("Impresiones");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Impresora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("AnchoMaximoMM")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInstalacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PuertoUSB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ResolucionDPI")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoMantenimiento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("MaquinaId")
                        .IsUnique();

                    b.ToTable("Impresoras");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadMaxima")
                        .HasColumnType("integer");

                    b.Property<string>("Cliente")
                        .HasColumnType("text");

                    b.Property<string>("CodigoProducto")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetaId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.LoteMaquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaDesasignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("MaquinaId");

                    b.ToTable("LotesMaquinas");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Maquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("DireccionMAC")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentificadorRed")
                        .HasColumnType("text");

                    b.Property<int>("LimiteImpresionDiario")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("DireccionMAC");

                    b.HasIndex("IdentificadorRed");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.ReglaImpresion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Autorizada")
                        .HasColumnType("boolean");

                    b.Property<int?>("CreadoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LimiteImpresiones")
                        .HasColumnType("integer");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("EtiquetaId");

                    b.HasIndex("MaquinaId");

                    b.ToTable("ReglasImpresion");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PuedeAdministrar")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeAutorizar")
                        .HasColumnType("boolean");

                    b.Property<bool>("PuedeImprimir")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Auditoria", b =>
                {
                    b.HasOne("SistemaImpresion.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Impresion", b =>
                {
                    b.HasOne("SistemaImpresion.Dominio.Entidades.Usuario", "AutorizadoPor")
                        .WithMany("ImpresionesAutorizadas")
                        .HasForeignKey("AutorizadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaImpresion.Dominio.Entidades.Empleado", "Empleado")
                        .WithMany("Impresiones")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaImpresion.Dominio.Entidades.Etiqueta", "Etiqueta")
                        .WithMany("Impresiones")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaImpresion.Dominio.Entidades.Impresora", "Impresora")
                        .WithMany("Impresiones")
                        .HasForeignKey("ImpresoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaImpresion.Dominio.Entidades.Lote", "Lote")
                        .WithMany("Impresiones")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaImpresion.Dominio.Entidades.Maquina", "Maquina")
                        .WithMany("Impresiones")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AutorizadoPor");

                    b.Navigation("Empleado");

                    b.Navigation("Etiqueta");

                    b.Navigation("Impresora");

                    b.Navigation("Lote");

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Impresora", b =>
                {
                    b.HasOne("SistemaImpresion.Dominio.Entidades.Maquina", "Maquina")
                        .WithOne("Impresora")
                        .HasForeignKey("SistemaImpresion.Dominio.Entidades.Impresora", "MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Lote", b =>
                {
                    b.HasOne("SistemaImpresion.Dominio.Entidades.Etiqueta", "Etiqueta")
                        .WithMany("Lotes")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etiqueta");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.LoteMaquina", b =>
                {
                    b.HasOne("SistemaImpresion.Dominio.Entidades.Lote", "Lote")
                        .WithMany("MaquinasAsignadas")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaImpresion.Dominio.Entidades.Maquina", "Maquina")
                        .WithMany("LotesAsignados")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.ReglaImpresion", b =>
                {
                    b.HasOne("SistemaImpresion.Dominio.Entidades.Usuario", "CreadoPor")
                        .WithMany("ReglasCreadas")
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaImpresion.Dominio.Entidades.Etiqueta", "Etiqueta")
                        .WithMany("Reglas")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaImpresion.Dominio.Entidades.Maquina", "Maquina")
                        .WithMany("Reglas")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("Etiqueta");

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("SistemaImpresion.Dominio.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Empleado", b =>
                {
                    b.Navigation("Impresiones");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Etiqueta", b =>
                {
                    b.Navigation("Impresiones");

                    b.Navigation("Lotes");

                    b.Navigation("Reglas");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Impresora", b =>
                {
                    b.Navigation("Impresiones");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Lote", b =>
                {
                    b.Navigation("Impresiones");

                    b.Navigation("MaquinasAsignadas");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Maquina", b =>
                {
                    b.Navigation("Impresiones");

                    b.Navigation("Impresora");

                    b.Navigation("LotesAsignados");

                    b.Navigation("Reglas");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaImpresion.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("ImpresionesAutorizadas");

                    b.Navigation("ReglasCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
